// All hardcoded demo data. No real patient or practice information.

export const DEMO_OFFICE = {
  id: "demo",
  name: "Demo Practice",
  location_code: "demo",
  active: true,
};

export const DEMO_STATS = {
  total_referrals: 24,
  exams_completed: 18,
  rewards_issued: 12,
  active_referrers: 47,
  top_referrers: [
    { id: "demo-r3", name: "Robert Kim",        total_referrals: 4, total_rewards_issued: 3 },
    { id: "demo-r1", name: "Mike Thompson",     total_referrals: 3, total_rewards_issued: 2 },
    { id: "demo-r2", name: "Lisa Chen",         total_referrals: 2, total_rewards_issued: 2 },
    { id: "demo-r5", name: "David Wilson",      total_referrals: 2, total_rewards_issued: 1 },
    { id: "demo-r4", name: "Jennifer Martinez", total_referrals: 1, total_rewards_issued: 0 },
  ],
  recent_events: [
    {
      id: "demo-e1",
      new_patient_name: "Sarah Johnson",
      new_patient_phone: "(615) 555-0101",
      referrer_id: "demo-r1",
      referrer_name: "Mike Thompson",
      team_source: "front",
      office: "Demo Practice",
      office_id: "demo",
      status: "Exam Completed",
      reward_type: null,
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "demo-e2",
      new_patient_name: "James Wilson",
      new_patient_phone: "(615) 555-0102",
      referrer_id: "demo-r2",
      referrer_name: "Lisa Chen",
      team_source: "back",
      office: "Demo Practice",
      office_id: "demo",
      status: "Reward Sent",
      reward_type: "amazon-gift-card",
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "demo-e3",
      new_patient_name: "Emily Davis",
      new_patient_phone: "(615) 555-0103",
      referrer_id: "demo-r3",
      referrer_name: "Robert Kim",
      team_source: "assistant",
      office: "Demo Practice",
      office_id: "demo",
      status: "Exam Completed",
      reward_type: null,
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "demo-e4",
      new_patient_name: "Michael Brown",
      new_patient_phone: "(615) 555-0104",
      referrer_id: "demo-r4",
      referrer_name: "Jennifer Martinez",
      team_source: "front",
      office: "Demo Practice",
      office_id: "demo",
      status: "Booked",
      reward_type: null,
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "demo-e5",
      new_patient_name: "Ashley Taylor",
      new_patient_phone: "(615) 555-0105",
      referrer_id: "demo-r5",
      referrer_name: "David Wilson",
      team_source: "back",
      office: "Demo Practice",
      office_id: "demo",
      status: "Reward Sent",
      reward_type: "in-house-credit",
      created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

export const DEMO_EVENTS = [
  {
    id: "demo-e1",
    new_patient_name: "Sarah Johnson",
    new_patient_phone: "(615) 555-0101",
    referrer_id: "demo-r1",
    referrer_name: "Mike Thompson",
    team_source: "front",
    office: "Demo Practice",
    status: "Exam Completed",
    reward_type: null,
    household_duplicate: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e2",
    new_patient_name: "James Wilson",
    new_patient_phone: "(615) 555-0102",
    referrer_id: "demo-r2",
    referrer_name: "Lisa Chen",
    team_source: "back",
    office: "Demo Practice",
    status: "Reward Sent",
    reward_type: "amazon-gift-card",
    household_duplicate: false,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e3",
    new_patient_name: "Emily Davis",
    new_patient_phone: "(615) 555-0103",
    referrer_id: "demo-r3",
    referrer_name: "Robert Kim",
    team_source: "assistant",
    office: "Demo Practice",
    status: "Exam Completed",
    reward_type: null,
    household_duplicate: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e4",
    new_patient_name: "Michael Brown",
    new_patient_phone: "(615) 555-0104",
    referrer_id: "demo-r4",
    referrer_name: "Jennifer Martinez",
    team_source: "front",
    office: "Demo Practice",
    status: "Booked",
    reward_type: null,
    household_duplicate: false,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e5",
    new_patient_name: "Ashley Taylor",
    new_patient_phone: "(615) 555-0105",
    referrer_id: "demo-r5",
    referrer_name: "David Wilson",
    team_source: "back",
    office: "Demo Practice",
    status: "Reward Sent",
    reward_type: "in-house-credit",
    household_duplicate: false,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e6",
    new_patient_name: "Christopher Anderson",
    new_patient_phone: "(615) 555-0106",
    referrer_id: "demo-r3",
    referrer_name: "Robert Kim",
    team_source: "front",
    office: "Demo Practice",
    status: "Exam Completed",
    reward_type: null,
    household_duplicate: false,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e7",
    new_patient_name: "Jessica Thomas",
    new_patient_phone: "(615) 555-0107",
    referrer_id: "demo-r1",
    referrer_name: "Mike Thompson",
    team_source: "assistant",
    office: "Demo Practice",
    status: "Lead",
    reward_type: null,
    household_duplicate: false,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-e8",
    new_patient_name: "Daniel Jackson",
    new_patient_phone: "(615) 555-0108",
    referrer_id: "demo-r2",
    referrer_name: "Lisa Chen",
    team_source: "back",
    office: "Demo Practice",
    status: "Reward Sent",
    reward_type: "charity-donation",
    household_duplicate: false,
    created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_REFERRERS = [
  {
    id: "demo-r1",
    name: "Mike Thompson",
    patient_id: "MIKE-1001",
    email: "mike.thompson@example.com",
    phone: "(615) 555-0201",
    referral_code: "MIKE1001",
    referral_url: "#",
    office_id: "demo",
    total_referrals: 3,
    total_rewards_issued: 2,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-r2",
    name: "Lisa Chen",
    patient_id: "LISA-1002",
    email: "lisa.chen@example.com",
    phone: "(615) 555-0202",
    referral_code: "LISA1002",
    referral_url: "#",
    office_id: "demo",
    total_referrals: 2,
    total_rewards_issued: 2,
    created_at: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-r3",
    name: "Robert Kim",
    patient_id: "ROBE-1003",
    email: "robert.kim@example.com",
    phone: "(615) 555-0203",
    referral_code: "ROBE1003",
    referral_url: "#",
    office_id: "demo",
    total_referrals: 4,
    total_rewards_issued: 3,
    created_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-r4",
    name: "Jennifer Martinez",
    patient_id: "JENN-1004",
    email: "jennifer.m@example.com",
    phone: "(615) 555-0204",
    referral_code: "JENN1004",
    referral_url: "#",
    office_id: "demo",
    total_referrals: 1,
    total_rewards_issued: 0,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-r5",
    name: "David Wilson",
    patient_id: "DAVI-1005",
    email: "david.wilson@example.com",
    phone: "(615) 555-0205",
    referral_code: "DAVI1005",
    referral_url: "#",
    office_id: "demo",
    total_referrals: 2,
    total_rewards_issued: 1,
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
